const E=[
['Linear',t=>t],['InSine',t=>1-Math.cos(t*Math.PI/2)],['OutSine',t=>Math.sin(t*Math.PI/2)],['InOutSine',t=>-(Math.cos(Math.PI*t)-1)/2],
['InQuad',t=>t*t],['OutQuad',t=>1-(1-t)**2],['InOutQuad',t=>t<.5?2*t*t:1-(-2*t+2)**2/2],
['InCubic',t=>t**3],['OutCubic',t=>1-(1-t)**3],['InOutCubic',t=>t<.5?4*t**3:1-(-2*t+2)**3/2],
['InQuart',t=>t**4],['OutQuart',t=>1-(1-t)**4],['InOutQuart',t=>t<.5?8*t**4:1-(-2*t+2)**4/2],
['InQuint',t=>t**5],['OutQuint',t=>1-(1-t)**5],['InOutQuint',t=>t<.5?16*t**5:1-(-2*t+2)**5/2],
['InExpo',t=>t===0?0:2**(10*t-10)],['OutExpo',t=>t===1?1:1-2**(-10*t)],['InOutExpo',t=>t===0?0:t===1?1:t<.5?2**(20*t-10)/2:(2-2**(-20*t+10))/2],
['InCirc',t=>1-Math.sqrt(1-t*t)],['OutCirc',t=>Math.sqrt(1-(t-1)**2)],['InOutCirc',t=>t<.5?(1-Math.sqrt(1-(2*t)**2))/2:(Math.sqrt(1-(-2*t+2)**2)+1)/2],
['InBack',t=>2.70158*t**3-1.70158*t**2],['OutBack',t=>1+2.70158*(t-1)**3+1.70158*(t-1)**2],['InOutBack',t=>{const c=2.5949095;return t<.5?((2*t)**2*((c+1)*2*t-c))/2:(((2*t-2)**2*((c+1)*(t*2-2)+c)+2)/2)}],
['InElastic',t=>t===0||t===1?t:-(2**(10*t-10))*Math.sin((t*10-10.75)*(2*Math.PI/3))],['OutElastic',t=>t===0||t===1?t:2**(-10*t)*Math.sin((t*10-.75)*(2*Math.PI/3))+1],['InOutElastic',t=>t===0||t===1?t:t<.5?-(2**(20*t-10)*Math.sin((20*t-11.125)*(2*Math.PI/4.5)))/2:(2**(-20*t+10)*Math.sin((20*t-11.125)*(2*Math.PI/4.5)))/2+1],
['InBounce',t=>1-bounce(1-t)],['OutBounce',bounce],['InOutBounce',t=>t<.5?(1-bounce(1-2*t))/2:(1+bounce(2*t-1))/2]];
function bounce(t){const n=7.5625,d=2.75;if(t<1/d)return n*t*t;if(t<2/d){t-=1.5/d;return n*t*t+.75}if(t<2.5/d){t-=2.25/d;return n*t*t+.9375}t-=2.625/d;return n*t*t+.984375}
const CANVAS_W=1600,CANVAS_H=900,$=id=>document.getElementById(id),clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),lerp=(a,b,t)=>a+(b-a)*t,map=Object.fromEntries(E);
function direction(n){if(n==='Linear')return'linear';if(n.startsWith('InOut'))return'inout';if(n.startsWith('In'))return'in';return'out'}function baseFamily(n){return n==='Linear'?'Linear':n.replace(/^(InOut|In|Out)/,'')}
const groupMap={};[['linear','Linear'],['in','Ease In'],['out','Ease Out'],['inout','Ease InOut']].forEach(([key,label])=>{const section=document.createElement('section');section.className='ease-group';section.dataset.group=key;section.innerHTML='<div class="ease-group-head"><h3>'+label+'</h3><span></span></div><div class="ease-group-grid"></div>';$('grid').append(section);groupMap[key]=section});
const tiles=E.map(([n],i)=>{const a=document.createElement('article');a.className='tile';a.dataset.family=baseFamily(n);a.innerHTML='<div class="tile-top"><span class="tile-name">'+n+'</span><span class="tile-code">'+String(i+1).padStart(2,'0')+'</span></div><div class="mini"><div class="base"></div><span class="point-line point-a"><b>A</b></span><span class="point-line point-b"><b>B</b></span><div class="object">EASE</div></div>';groupMap[direction(n)].lastChild.append(a);return a});
const familyNames=['Linear','Sine','Quad','Cubic','Quart','Quint','Expo','Circ','Back','Elastic','Bounce'],selectedFamilies=new Set;
function applyOverviewFamily(){let total=0;tiles.forEach(tile=>{tile.hidden=selectedFamilies.size>0&&!selectedFamilies.has(tile.dataset.family);if(!tile.hidden)total++});Object.values(groupMap).forEach(group=>{const count=[...group.querySelectorAll('.tile')].filter(tile=>!tile.hidden).length;group.hidden=count===0;group.querySelector('.ease-group-head span').textContent=count+' types'});$('visibleCount').textContent=total;$('overviewFamilyFilter').querySelectorAll('button').forEach(button=>{const active=button.dataset.overviewFamily==='All'?selectedFamilies.size===0:selectedFamilies.has(button.dataset.overviewFamily);button.classList.toggle('active',active);button.setAttribute('aria-pressed',active)})}
['All',...familyNames].forEach(name=>{const button=document.createElement('button');button.type='button';button.textContent=name;button.dataset.overviewFamily=name;button.title=name==='All'?'Show every family':'Toggle '+name;button.onclick=()=>{if(name==='All')selectedFamilies.clear();else if(selectedFamilies.has(name))selectedFamilies.delete(name);else selectedFamilies.add(name);applyOverviewFamily()};$('overviewFamilyFilter').append(button)});applyOverviewFamily();
const envelopes=E.map(([,fn])=>{let min=0,max=1;for(let i=0;i<=400;i++){const q=fn(i/400);min=Math.min(min,q);max=Math.max(max,q)}return{min,max}}),sharedEnvelope=envelopes.reduce((all,env)=>({min:Math.min(all.min,env.min),max:Math.max(all.max,env.max)}),{min:0,max:1});
const overviewStart=performance.now();function overview(now){const p=Math.min(1,((now-overviewStart)%2400)/1850),move=$('overviewTransform').checked,scale=$('overviewScale').checked,rotate=$('overviewRotation').checked;tiles.forEach((tile,i)=>{if(tile.hidden)return;const stage=tile.lastChild,o=stage.lastChild,q=E[i][1](p),env=sharedEnvelope,safeLeft=30,safeRight=stage.clientWidth-o.offsetWidth-30,travel=(safeRight-safeLeft)/Math.max(.001,env.max-env.min),a=safeLeft-env.min*travel,b=a+travel,center=(stage.clientWidth-o.offsetWidth)/2,lines=stage.querySelectorAll('.point-line');o.style.left=(move?lerp(a,b,q):center)+'px';o.style.transform='scale('+(scale?lerp(.58,1.36,q):1.08)+') rotate('+(rotate?lerp(0,360,q):0)+'deg)';o.textContent=rotate?'EASE':'';lines[0].style.left=(a+o.offsetWidth/2)+'px';lines[1].style.left=(b+o.offsetWidth/2)+'px';lines.forEach(line=>line.style.display=move?'block':'none')});requestAnimationFrame(overview)}requestAnimationFrame(overview);
const tabs=[$('overviewTab'),$('experimentTab')];tabs.forEach(tab=>tab.onclick=()=>{const exp=tab===$('experimentTab');$('overviewPanel').hidden=exp;$('experimentPanel').hidden=!exp;tabs.forEach(x=>{const yes=x===tab;x.classList.toggle('active',yes);x.setAttribute('aria-selected',yes)});if(exp)requestAnimationFrame(()=>{renderAll();restart()})});
const channelDefaults={transform:{enabled:true,family:'Cubic',direction:'InOut'},scale:{enabled:true,family:'Back',direction:'Out'},rotation:{enabled:true,family:'Sine',direction:'InOut'}};
function makeChannels(source=channelDefaults){return Object.fromEntries(Object.entries(source).map(([name,config])=>[name,{...config}]))}
let activeChannel='transform';
const easeFamilies=['Linear','Sine','Quad','Cubic','Quart','Quint','Expo','Circ','Back','Elastic','Bounce'],easeDirections=['In','Out','InOut'];
easeFamilies.forEach(name=>{const b=document.createElement('button');b.type='button';b.className='ease-choice';b.dataset.family=name;b.textContent=name;$('familyOptions').append(b)});
easeDirections.forEach(name=>{const b=document.createElement('button');b.type='button';b.className='ease-choice';b.dataset.direction=name;b.textContent=name;$('directionOptions').append(b)});
function configEase(c){return c.family==='Linear'?'Linear':c.direction+c.family}
function renderEaseEditor(){const p=points.find(p=>p.id===selected)||points[0],pointIndex=points.indexOf(p),hasIncoming=pointIndex>0,c=p.channels[activeChannel];document.querySelectorAll('.property-tab').forEach(b=>{b.classList.toggle('active',b.dataset.channel===activeChannel);b.classList.toggle('off',hasIncoming&&!p.channels[b.dataset.channel].enabled);b.setAttribute('aria-pressed',b.dataset.channel===activeChannel)});$('channelEnabled').checked=hasIncoming?c.enabled:true;$('channelEnabled').disabled=!hasIncoming;$('channelEnabledLabel').textContent=hasIncoming?'Enabled for Point '+(pointIndex+1):'Start point';$('selectedEase').textContent=(hasIncoming?'Point '+(pointIndex+1)+' · ':'Start · ')+'EaseType.'+configEase(c);document.querySelectorAll('[data-family]').forEach(b=>{b.classList.toggle('active',b.dataset.family===c.family);b.setAttribute('aria-pressed',b.dataset.family===c.family)});document.querySelectorAll('[data-direction]').forEach(b=>{const on=c.family!=='Linear'&&b.dataset.direction===c.direction;b.disabled=c.family==='Linear';b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)})}
document.querySelectorAll('.property-tab').forEach(b=>b.onclick=()=>{activeChannel=b.dataset.channel;syncHistoryContext();renderEaseEditor()});
$('familyOptions').onclick=e=>{const b=e.target.closest('[data-family]'),p=points.find(p=>p.id===selected);if(!b||!p)return;p.channels[activeChannel].family=b.dataset.family;commitHistory();renderEaseEditor();restartFromPreviousPoint()};
$('directionOptions').onclick=e=>{const b=e.target.closest('[data-direction]'),p=points.find(p=>p.id===selected);if(!b||!p)return;p.channels[activeChannel].direction=b.dataset.direction;commitHistory();renderEaseEditor();restartFromPreviousPoint()};
$('channelEnabled').onchange=e=>{const p=points.find(p=>p.id===selected),pointIndex=points.indexOf(p);if(!p||pointIndex===0)return;p.channels[activeChannel].enabled=e.target.checked;commitHistory();renderEaseEditor();restartFromPreviousPoint()};
let nextId=3,points=[{id:1,x:100,y:300,scale:.65,rotation:-35,channels:makeChannels()},{id:2,x:700,y:300,scale:1.35,rotation:360,duration:1200,channels:makeChannels()}],selected=1,rowDrag=null,pointDrag=null,gizmoDrag=null,start=performance.now(),paused=0,playing=true,scrubbing=false,history=[],historyIndex=-1;
document.querySelector('.hint').textContent='Keep at least 2 points. Select one and press Delete to remove it.';
function cloneState(value){return JSON.parse(JSON.stringify(value))}function currentHistoryState(){return{points:cloneState(points),nextId,selected,activeChannel}}function updateHistoryButtons(){$('undo').disabled=historyIndex<=0;$('redo').disabled=historyIndex>=history.length-1}function commitHistory(){const state=currentHistoryState(),current=history[historyIndex];if(current&&JSON.stringify(current)===JSON.stringify(state)){updateHistoryButtons();return}history=history.slice(0,historyIndex+1);history.push(state);if(history.length>100)history.shift();historyIndex=history.length-1;updateHistoryButtons()}function syncHistoryContext(){if(historyIndex<0)return;history[historyIndex].selected=selected;history[historyIndex].activeChannel=activeChannel}function restoreHistory(index){if(index<0||index>=history.length)return;const state=history[index];historyIndex=index;points=cloneState(state.points);nextId=state.nextId;selected=points.some(p=>p.id===state.selected)?state.selected:points.at(-1).id;activeChannel=state.activeChannel||activeChannel;rowDrag=pointDrag=gizmoDrag=null;renderAll();restart();updateHistoryButtons()}function undo(){restoreHistory(historyIndex-1)}function redo(){restoreHistory(historyIndex+1)}commitHistory();
function bounds(){return{w:CANVAS_W,h:CANVAS_H}}function norm(p){return Object.assign({},p,{x:clamp(p.x,0,CANVAS_W),y:clamp(p.y,0,CANVAS_H)})}function updateCanvasScale(){const viewer=$('viewer');if(viewer.clientWidth)$('canvas').style.setProperty('--canvas-scale',viewer.clientWidth/CANVAS_W)}
function restart(){start=performance.now();paused=0}function restartFromPreviousPoint(){const index=points.findIndex(p=>p.id===selected);if(index>0)seekToPoint(points[index-1].id);else restart()}function setPlayback(next){if(next===playing)return;if(next)start=performance.now()-paused;else paused=performance.now()-start;playing=next;$('play').textContent=playing?'❚❚ Pause':'▶ Play'}
function addAt(x,y){const prev=points.at(-1),p=norm({id:nextId++,x:Math.round(x),y:Math.round(y),scale:prev.scale,rotation:(Math.floor(prev.rotation/360)+1)*360,duration:800,channels:makeChannels(prev.channels)});points.push(p);selected=p.id;commitHistory();renderAll();restart()}
function del(id){if(points.length<=2)return;const i=points.findIndex(p=>p.id===id);points.splice(i,1);selected=points[Math.min(i,points.length-1)].id;commitHistory();renderAll();restart()}
function reorder(a,b){if(a===b)return;const i=points.findIndex(p=>p.id===a),j=points.findIndex(p=>p.id===b);if(i<0||j<0)return;const p=points.splice(i,1)[0];points.splice(j,0,p);commitHistory();renderAll();restart()}
function focusPoint(p,row,list){if(selected===p.id)return;selected=p.id;syncHistoryContext();list.querySelectorAll('.point-row').forEach(r=>r.classList.toggle('selected',r===row));renderMarkers();renderEaseEditor()}
function renderList(){const list=$('pointList');list.innerHTML='';points.forEach((p,i)=>{const row=document.createElement('div');let dragAllowed=false;row.className='point-row'+(p.id===selected?' selected':'');row.tabIndex=-1;row.innerHTML='<span class="handle" title="Drag point to reorder">⠿</span><span class="index">'+(i+1)+'</span><div class="point-fields">'+field('x','X',Math.round(p.x))+field('y','Y',Math.round(p.y))+field('scale','Scale',Number(p.scale.toFixed(2)))+field('rotation','Rotate °',Math.round(p.rotation))+(i?field('duration','From prev ms',Math.round(pointDuration(p))):'')+'</div><button class="button icon-btn danger" data-a="delete" aria-label="Delete point" title="Delete point" '+(points.length<=2?'disabled':'')+'>🗑</button>';row.onpointerdown=e=>{dragAllowed=!e.target.closest('input,button');if(!dragAllowed)return;row.focus({preventScroll:true});focusPoint(p,row,list)};row.onclick=e=>{if(e.target.closest('[data-a=delete]'))return;focusPoint(p,row,list)};row.querySelectorAll('input').forEach(input=>{input.onfocus=()=>focusPoint(p,row,list);input.oninput=e=>{if(e.target.value==='')return;const k=e.target.dataset.key,v=Number(e.target.value);if(!Number.isFinite(v))return;p[k]=k==='scale'?Math.max(0,v):k==='duration'?Math.max(50,v):v;if(k==='x'||k==='y')Object.assign(p,norm(p));renderMarkers();restart()};input.onchange=()=>{commitHistory();renderAll();restart()}});row.querySelector('[data-a=delete]').onclick=e=>{e.stopPropagation();del(p.id)};row.draggable=true;row.ondragstart=e=>{if(!dragAllowed){e.preventDefault();return}rowDrag=p.id;row.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(p.id))};row.ondragend=()=>{rowDrag=null;row.classList.remove('dragging');list.querySelectorAll('.drag-over').forEach(r=>r.classList.remove('drag-over'))};row.ondragover=e=>{if(rowDrag==null)return;e.preventDefault();row.classList.add('drag-over')};row.ondragleave=e=>{if(!row.contains(e.relatedTarget))row.classList.remove('drag-over')};row.ondrop=e=>{if(rowDrag==null)return;e.preventDefault();row.classList.remove('drag-over');reorder(rowDrag,p.id)};list.append(row)})}
function field(k,l,v){return'<div class="field"><label>'+l+'</label><input data-key="'+k+'" type="number" value="'+v+'" step="'+(k==='scale'?'.05':k==='duration'?'50':'1')+'"></div>'}
function renderMarkers(){const box=$('markers');box.innerHTML='';points.forEach((p,i)=>{Object.assign(p,norm(p));const m=document.createElement('button');m.type='button';m.className='marker'+(p.id===selected?' selected':'');m.dataset.id=p.id;m.dataset.values='s '+p.scale.toFixed(2)+' · r '+Math.round(p.rotation)+'°';m.style.left=p.x+'px';m.style.top=p.y+'px';m.textContent=i+1;m.setAttribute('aria-label','Point '+(i+1));m.onclick=e=>{e.stopPropagation();selected=p.id;syncHistoryContext();renderAll()};m.onpointerdown=e=>{e.stopPropagation();selected=p.id;syncHistoryContext();pointDrag=p.id;m.setPointerCapture(e.pointerId);renderList();m.classList.add('selected')};m.onpointermove=e=>{if(pointDrag!==p.id)return;updatePoint(p,e,m)};m.onpointerup=e=>{if(pointDrag!==p.id)return;updatePoint(p,e,m);pointDrag=null;commitHistory();guides();renderAll()};m.onpointercancel=()=>{if(pointDrag===p.id)commitHistory();pointDrag=null;guides();renderAll()};box.append(m)});const p=points.find(p=>p.id===selected);if(p){const g=document.createElement('div');g.className='point-gizmo';g.style.left=p.x+'px';g.style.top=p.y+'px';g.style.setProperty('--point-rotation',p.rotation+'deg');g.innerHTML='<span class="gizmo-axis"></span><button class="gizmo-handle gizmo-rotate" type="button" title="Drag to rotate">R</button><button class="gizmo-handle gizmo-scale" type="button" title="Drag to scale">S</button>';box.append(g);bindGizmo(g,p)}$('pathLine').setAttribute('points',points.map(p=>p.x+','+p.y).join(' '))}
function bindGizmo(g,p){const rotate=g.querySelector('.gizmo-rotate'),scale=g.querySelector('.gizmo-scale');rotate.onpointerdown=e=>{e.stopPropagation();rotate.setPointerCapture(e.pointerId);const c=coords(e);beginGizmoDrag({type:'rotate',id:p.id,lastAngle:Math.atan2(c.y-p.y,c.x-p.x)*180/Math.PI})};rotate.onpointermove=e=>{if(!gizmoDrag||gizmoDrag.type!=='rotate'||gizmoDrag.id!==p.id)return;const c=coords(e),angle=Math.atan2(c.y-p.y,c.x-p.x)*180/Math.PI,delta=((angle-gizmoDrag.lastAngle+540)%360)-180;p.rotation+=delta;gizmoDrag.lastAngle=angle;g.style.setProperty('--point-rotation',p.rotation+'deg');liveGizmo(p)};scale.onpointerdown=e=>{e.stopPropagation();scale.setPointerCapture(e.pointerId);const c=coords(e);beginGizmoDrag({type:'scale',id:p.id,startDistance:Math.max(1,Math.hypot(c.x-p.x,c.y-p.y)),startScale:p.scale})};scale.onpointermove=e=>{if(!gizmoDrag||gizmoDrag.type!=='scale'||gizmoDrag.id!==p.id)return;const c=coords(e);p.scale=Math.max(.05,gizmoDrag.startScale*Math.hypot(c.x-p.x,c.y-p.y)/gizmoDrag.startDistance);liveGizmo(p)};[rotate,scale].forEach(handle=>{handle.onpointerup=finishGizmoDrag;handle.onpointercancel=finishGizmoDrag})}
function previewPoint(id){const p=points.find(p=>p.id===id);if(!p)return;const o=$('outputObject');o.style.left=p.x+'px';o.style.top=p.y+'px';o.style.transform='translate(-50%,-50%) scale('+p.scale+') rotate('+p.rotation+'deg)'}function pointDuration(p){return Math.max(50,Number(p.duration)||800)}
function pointTimeline(id){const index=points.findIndex(p=>p.id===id);return points.slice(1,Math.max(1,index+1)).reduce((total,p)=>total+pointDuration(p),0)}
function beginGizmoDrag(state){state.wasPlaying=playing;if(playing)setPlayback(false);seekToPoint(state.id);gizmoDrag=state;previewPoint(state.id)}
function finishGizmoDrag(){if(!gizmoDrag)return;const state=gizmoDrag,resume=state.wasPlaying;if(playing)setPlayback(false);gizmoDrag=null;commitHistory();renderAll();seekToPoint(state.id);if(resume)setPlayback(true)}
function liveGizmo(p){const marker=document.querySelector('.marker[data-id="'+p.id+'"]');if(marker)marker.dataset.values='s '+p.scale.toFixed(2)+' · r '+Math.round(p.rotation)+'°';previewPoint(p.id)}
function renderAll(){updateCanvasScale();renderList();renderMarkers();renderEaseEditor()}

function coords(e){const viewer=$('viewer'),r=viewer.getBoundingClientRect(),x=(e.clientX-r.left-viewer.clientLeft)/viewer.clientWidth*CANVAS_W,y=(e.clientY-r.top-viewer.clientTop)/viewer.clientHeight*CANVAS_H;return{x:clamp(x,0,CANVAS_W),y:clamp(y,0,CANVAS_H)}}
function snap(c,exclude){const q=points.filter(p=>p.id!==exclude);if(!q.length)return Object.assign(c,{gx:null,gy:null});const px=q.reduce((a,p)=>Math.abs(p.x-c.x)<Math.abs(a.x-c.x)?p:a),py=q.reduce((a,p)=>Math.abs(p.y-c.y)<Math.abs(a.y-c.y)?p:a);return Math.abs(px.x-c.x)<=Math.abs(py.y-c.y)?{x:px.x,y:c.y,gx:px.x,gy:null}:{x:c.x,y:py.y,gx:null,gy:py.y}}
function guides(x=null,y=null){$('vGuide').style.display=x==null?'none':'block';$('hGuide').style.display=y==null?'none':'block';if(x!=null)$('vGuide').style.left=x+'px';if(y!=null)$('hGuide').style.top=y+'px'}
function updatePoint(p,e,m){let c=coords(e);if(e.shiftKey)c=snap(c,p.id);else c.gx=c.gy=null;Object.assign(p,norm(Object.assign({},p,c)));m.style.left=p.x+'px';m.style.top=p.y+'px';m.dataset.values='s '+p.scale.toFixed(2)+' · r '+Math.round(p.rotation)+'°';$('pathLine').setAttribute('points',points.map(x=>x.x+','+x.y).join(' '));guides(c.gx,c.gy);restart()}
$('viewer').onclick=e=>{if(e.target.closest('.marker')||e.target.closest('.object')||e.target.closest('.point-gizmo'))return;let c=coords(e);if(e.shiftKey)c=snap(c);addAt(c.x,c.y);guides(c.gx,c.gy);setTimeout(()=>guides(),500)};
$('addPoint').onclick=()=>{const a=points.at(-1),bd=bounds();addAt(clamp(a.x+70,30,bd.w-30),clamp(a.y+55,30,bd.h-30))};
$('addCenter').onclick=()=>{const b=bounds();addAt(b.w/2,b.h/2)};
document.addEventListener('keydown',e=>{if(e.key!=='Delete'||e.target.matches('input,textarea,select,[contenteditable="true"]'))return;e.preventDefault();del(selected)});
document.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey)||e.altKey||$('experimentPanel').hidden||e.target.matches('input,textarea,select,[contenteditable="true"]'))return;const key=e.key.toLowerCase();if(key==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if(key==='y'){e.preventDefault();redo()}});
document.addEventListener('keydown',e=>{if(e.code!=='Space'||$('experimentPanel').hidden||e.repeat)return;e.preventDefault();setPlayback(!playing)});$('restart').onclick=restart;$('play').onclick=()=>setPlayback(!playing);$('undo').onclick=undo;$('redo').onclick=redo;
function channel(n,point){const c=point.channels[n];return{on:c.enabled,fn:map[configEase(c)]||map.Linear}}function effectiveValue(pointIndex,channelName,key){let value=points[0][key];for(let i=1;i<=pointIndex;i++)if(points[i].channels[channelName].enabled)value=points[i][key];return value}
function timing(){const count=points.length-1,durations=points.slice(1).map(pointDuration),motionTotal=durations.reduce((sum,value)=>sum+value,0),endPause=450;return{count,durations,motionTotal,endPause,cycle:Math.max(50,motionTotal+endPause)}}
function updateTimeline(elapsed,total){const visible=clamp(elapsed,0,total),value=clamp(visible/total,0,1);if(!scrubbing)$('timelineSlider').value=Math.round(value*1000);$('timelineCurrent').textContent=(visible/1000).toFixed(2)+'s';$('timelineTotal').textContent=(total/1000).toFixed(2)+'s'}
const timelineSlider=$('timelineSlider');timelineSlider.onpointerdown=()=>{scrubbing=true;if(playing)setPlayback(false)};timelineSlider.oninput=e=>{if(playing)setPlayback(false);const info=timing();paused=Number(e.target.value)/1000*info.motionTotal;start=performance.now()-paused;updateTimeline(paused,info.motionTotal)};timelineSlider.onpointerup=()=>{scrubbing=false};timelineSlider.onpointercancel=()=>{scrubbing=false};timelineSlider.onchange=()=>{scrubbing=false};
function renderAtTime(elapsed,info=timing()){const{count,durations,motionTotal,cycle}=info;elapsed=clamp(elapsed,0,cycle);let seg=count-1,local=1;if(elapsed<motionTotal){let cursor=0;for(let i=0;i<count;i++){if(elapsed<cursor+durations[i]){seg=i;local=(elapsed-cursor)/durations[i];break}cursor+=durations[i]}}const a=points[seg],b=points[seg+1],tr=channel('transform',b),sc=channel('scale',b),ro=channel('rotation',b),startX=effectiveValue(seg,'transform','x'),startY=effectiveValue(seg,'transform','y'),startScale=effectiveValue(seg,'scale','scale'),startRotation=effectiveValue(seg,'rotation','rotation'),x=tr.on?lerp(startX,b.x,tr.fn(local)):startX,y=tr.on?lerp(startY,b.y,tr.fn(local)):startY,s=sc.on?lerp(startScale,b.scale,sc.fn(local)):startScale,r=ro.on?lerp(startRotation,b.rotation,ro.fn(local)):startRotation,o=$('outputObject');o.style.left=x+'px';o.style.top=y+'px';o.style.transform='translate(-50%,-50%) scale('+s+') rotate('+r+'deg)';$('readout').textContent=(Math.min(elapsed,motionTotal)/1000).toFixed(2)+' s · '+(elapsed>=motionTotal?'restart pause':'segment '+(seg+1)+'/'+count);updateTimeline(elapsed,motionTotal)}
function seekToPoint(id){const info=timing();paused=clamp(pointTimeline(id),0,info.motionTotal);start=performance.now()-paused;renderAtTime(paused,info)}
function animate(now){if(gizmoDrag){requestAnimationFrame(animate);return}if(!$('experimentPanel').hidden&&points.length>1){const info=timing();let elapsed=playing?now-start:paused;if(elapsed>=info.cycle){if(playing){start=now;elapsed=0}else elapsed=info.cycle}renderAtTime(elapsed,info)}requestAnimationFrame(animate)}requestAnimationFrame(animate);
new ResizeObserver(()=>{updateCanvasScale();points=points.map(norm);renderMarkers()}).observe($('viewer'));
